version: '3.8'
services:
  db:
    image: postgres
    container_name: nest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: nest
